//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Domashnee_zadanie_Pokataeva
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дистанция.
    /// </summary>
    //  *** Start programmer edit section *** (Дистанция CustomAttributes)

    //  *** End programmer edit section *** (Дистанция CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДистанцияE", new string[] {
            "Длина as \'Длина\'"})]
    [AssociatedDetailViewAttribute("ДистанцияE", "УчастникиДистанции", "УчастникиДистанцииE", true, "", "Участники дистанции", true, new string[] {
            ""})]
    [View("ДистанцияL", new string[] {
            "Длина as \'Длина\'"})]
    public class Дистанция : ICSSoft.STORMNET.DataObject
    {
        
        private int fДлина;
        
        private IIS.Domashnee_zadanie_Pokataeva.DetailArrayOfУчастникиДистанции fУчастникиДистанции;
        
        //  *** Start programmer edit section *** (Дистанция CustomMembers)

        //  *** End programmer edit section *** (Дистанция CustomMembers)

        
        /// <summary>
        /// Длина.
        /// </summary>
        //  *** Start programmer edit section *** (Дистанция.Длина CustomAttributes)

        //  *** End programmer edit section *** (Дистанция.Длина CustomAttributes)
        public virtual int Длина
        {
            get
            {
                //  *** Start programmer edit section *** (Дистанция.Длина Get start)

                //  *** End programmer edit section *** (Дистанция.Длина Get start)
                int result = this.fДлина;
                //  *** Start programmer edit section *** (Дистанция.Длина Get end)

                //  *** End programmer edit section *** (Дистанция.Длина Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Дистанция.Длина Set start)

                //  *** End programmer edit section *** (Дистанция.Длина Set start)
                this.fДлина = value;
                //  *** Start programmer edit section *** (Дистанция.Длина Set end)

                //  *** End programmer edit section *** (Дистанция.Длина Set end)
            }
        }
        
        /// <summary>
        /// Дистанция.
        /// </summary>
        //  *** Start programmer edit section *** (Дистанция.УчастникиДистанции CustomAttributes)

        //  *** End programmer edit section *** (Дистанция.УчастникиДистанции CustomAttributes)
        public virtual IIS.Domashnee_zadanie_Pokataeva.DetailArrayOfУчастникиДистанции УчастникиДистанции
        {
            get
            {
                //  *** Start programmer edit section *** (Дистанция.УчастникиДистанции Get start)

                //  *** End programmer edit section *** (Дистанция.УчастникиДистанции Get start)
                if ((this.fУчастникиДистанции == null))
                {
                    this.fУчастникиДистанции = new IIS.Domashnee_zadanie_Pokataeva.DetailArrayOfУчастникиДистанции(this);
                }
                IIS.Domashnee_zadanie_Pokataeva.DetailArrayOfУчастникиДистанции result = this.fУчастникиДистанции;
                //  *** Start programmer edit section *** (Дистанция.УчастникиДистанции Get end)

                //  *** End programmer edit section *** (Дистанция.УчастникиДистанции Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Дистанция.УчастникиДистанции Set start)

                //  *** End programmer edit section *** (Дистанция.УчастникиДистанции Set start)
                this.fУчастникиДистанции = value;
                //  *** Start programmer edit section *** (Дистанция.УчастникиДистанции Set end)

                //  *** End programmer edit section *** (Дистанция.УчастникиДистанции Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДистанцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДистанцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДистанцияE", typeof(IIS.Domashnee_zadanie_Pokataeva.Дистанция));
                }
            }
            
            /// <summary>
            /// "ДистанцияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДистанцияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДистанцияL", typeof(IIS.Domashnee_zadanie_Pokataeva.Дистанция));
                }
            }
        }
    }
}
