//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Domashnee_zadanie_Pokataeva
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участники дистанции.
    /// </summary>
    //  *** Start programmer edit section *** (УчастникиДистанции CustomAttributes)

    //  *** End programmer edit section *** (УчастникиДистанции CustomAttributes)
    [AutoAltered()]
    [Caption("Участники дистанции")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчастникиДистанцииE", new string[] {
            "Участник as \'Участник\'",
            "Участник.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Участник.ФИО"})]
    [MasterViewDefineAttribute("УчастникиДистанцииE", "Участник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class УчастникиДистанции : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Domashnee_zadanie_Pokataeva.Участник fУчастник;
        
        private IIS.Domashnee_zadanie_Pokataeva.Дистанция fДистанция;
        
        //  *** Start programmer edit section *** (УчастникиДистанции CustomMembers)

        //  *** End programmer edit section *** (УчастникиДистанции CustomMembers)

        
        /// <summary>
        /// Участники дистанции.
        /// </summary>
        //  *** Start programmer edit section *** (УчастникиДистанции.Участник CustomAttributes)

        //  *** End programmer edit section *** (УчастникиДистанции.Участник CustomAttributes)
        [NotNull()]
        public virtual IIS.Domashnee_zadanie_Pokataeva.Участник Участник
        {
            get
            {
                //  *** Start programmer edit section *** (УчастникиДистанции.Участник Get start)

                //  *** End programmer edit section *** (УчастникиДистанции.Участник Get start)
                IIS.Domashnee_zadanie_Pokataeva.Участник result = this.fУчастник;
                //  *** Start programmer edit section *** (УчастникиДистанции.Участник Get end)

                //  *** End programmer edit section *** (УчастникиДистанции.Участник Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (УчастникиДистанции.Участник Set start)

                //  *** End programmer edit section *** (УчастникиДистанции.Участник Set start)
                this.fУчастник = value;
                //  *** Start programmer edit section *** (УчастникиДистанции.Участник Set end)

                //  *** End programmer edit section *** (УчастникиДистанции.Участник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Domashnee_zadanie_Pokataeva.Дистанция.
        /// </summary>
        //  *** Start programmer edit section *** (УчастникиДистанции.Дистанция CustomAttributes)

        //  *** End programmer edit section *** (УчастникиДистанции.Дистанция CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Domashnee_zadanie_Pokataeva.Дистанция Дистанция
        {
            get
            {
                //  *** Start programmer edit section *** (УчастникиДистанции.Дистанция Get start)

                //  *** End programmer edit section *** (УчастникиДистанции.Дистанция Get start)
                IIS.Domashnee_zadanie_Pokataeva.Дистанция result = this.fДистанция;
                //  *** Start programmer edit section *** (УчастникиДистанции.Дистанция Get end)

                //  *** End programmer edit section *** (УчастникиДистанции.Дистанция Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (УчастникиДистанции.Дистанция Set start)

                //  *** End programmer edit section *** (УчастникиДистанции.Дистанция Set start)
                this.fДистанция = value;
                //  *** Start programmer edit section *** (УчастникиДистанции.Дистанция Set end)

                //  *** End programmer edit section *** (УчастникиДистанции.Дистанция Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчастникиДистанцииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникиДистанцииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникиДистанцииE", typeof(IIS.Domashnee_zadanie_Pokataeva.УчастникиДистанции));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of УчастникиДистанции.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfУчастникиДистанции CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfУчастникиДистанции CustomAttributes)
    public class DetailArrayOfУчастникиДистанции : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Domashnee_zadanie_Pokataeva.DetailArrayOfУчастникиДистанции members)

        //  *** End programmer edit section *** (IIS.Domashnee_zadanie_Pokataeva.DetailArrayOfУчастникиДистанции members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type УчастникиДистанции by index.
        /// </summary>
        /// <summary>
        /// Adds object with type УчастникиДистанции.
        /// </summary>
        public DetailArrayOfУчастникиДистанции(IIS.Domashnee_zadanie_Pokataeva.Дистанция fДистанция) : 
                base(typeof(УчастникиДистанции), ((ICSSoft.STORMNET.DataObject)(fДистанция)))
        {
        }
        
        public IIS.Domashnee_zadanie_Pokataeva.УчастникиДистанции this[int index]
        {
            get
            {
                return ((IIS.Domashnee_zadanie_Pokataeva.УчастникиДистанции)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Domashnee_zadanie_Pokataeva.УчастникиДистанции dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
