//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Domashnee_zadanie_Pokataeva
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участник.
    /// </summary>
    //  *** Start programmer edit section *** (Участник CustomAttributes)

    //  *** End programmer edit section *** (Участник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчастникE", new string[] {
            "ФИО as \'ФИО\'",
            "Команда as \'Команда\'",
            "Команда.Название as \'Название\'"})]
    [View("УчастникL", new string[] {
            "ФИО as \'ФИО\'",
            "Команда.Название as \'Название\'"})]
    public class Участник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Domashnee_zadanie_Pokataeva.Команда fКоманда;
        
        //  *** Start programmer edit section *** (Участник CustomMembers)

        //  *** End programmer edit section *** (Участник CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        //  *** Start programmer edit section *** (Участник.ФИО CustomAttributes)

        //  *** End programmer edit section *** (Участник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                //  *** Start programmer edit section *** (Участник.ФИО Get start)

                //  *** End programmer edit section *** (Участник.ФИО Get start)
                string result = this.fФИО;
                //  *** Start programmer edit section *** (Участник.ФИО Get end)

                //  *** End programmer edit section *** (Участник.ФИО Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Участник.ФИО Set start)

                //  *** End programmer edit section *** (Участник.ФИО Set start)
                this.fФИО = value;
                //  *** Start programmer edit section *** (Участник.ФИО Set end)

                //  *** End programmer edit section *** (Участник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Участник.
        /// </summary>
        //  *** Start programmer edit section *** (Участник.Команда CustomAttributes)

        //  *** End programmer edit section *** (Участник.Команда CustomAttributes)
        [NotNull()]
        public virtual IIS.Domashnee_zadanie_Pokataeva.Команда Команда
        {
            get
            {
                //  *** Start programmer edit section *** (Участник.Команда Get start)

                //  *** End programmer edit section *** (Участник.Команда Get start)
                IIS.Domashnee_zadanie_Pokataeva.Команда result = this.fКоманда;
                //  *** Start programmer edit section *** (Участник.Команда Get end)

                //  *** End programmer edit section *** (Участник.Команда Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Участник.Команда Set start)

                //  *** End programmer edit section *** (Участник.Команда Set start)
                this.fКоманда = value;
                //  *** Start programmer edit section *** (Участник.Команда Set end)

                //  *** End programmer edit section *** (Участник.Команда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчастникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникE", typeof(IIS.Domashnee_zadanie_Pokataeva.Участник));
                }
            }
            
            /// <summary>
            /// "УчастникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастникL", typeof(IIS.Domashnee_zadanie_Pokataeva.Участник));
                }
            }
        }
    }
}
